# Generated by Django 4.2.3 on 2023-07-14 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movielist", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moivedata",
            name="rating_aud",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="moivedata",
            name="rating_cri",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="moivedata",
            name="rating_net",
            field=models.CharField(max_length=100),
        ),
    ]
