# Generated by Django 4.2.3 on 2023-07-14 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movielist", "0004_alter_moivedata_title_kor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moivedata",
            name="title_kor",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
