# Generated by Django 4.2.3 on 2023-07-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movielist", "0007_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rating",
            name="rating_cnt",
        ),
        migrations.RemoveField(
            model_name="rating",
            name="rating_sum",
        ),
        migrations.AddField(
            model_name="rating",
            name="rating",
            field=models.FloatField(default=0),
        ),
    ]
