# Generated by Django 4.2.3 on 2023-07-14 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email',
        ),
    ]
